version: '2'
services:
  zookeeper:
    image: quay.io/debezium/zookeeper:2.1
    ports:
     - 2181:2181
  kafka:
    image: quay.io/debezium/kafka:2.1
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
  connect:
    image: debezium/connect-jdbc-es:2.1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEBEZIUM_VERSION: 2.1
    volumes:
      - ./jar/mysql-connector-j-8.1.0.jar:/kafka/connect/kafka-connect-jdbc/mysql-connector-j-8.1.0.jar
      - ./jar/mssql-jdbc-7.2.2.jre11.jar:/kafka/connect/kafka-connect-jdbc/mssql-jdbc-7.2.2.jre11.jar
      - ./jar/jtds-1.3.1.jar:/kafka/connect/kafka-connect-jdbc/jtds-1.3.1.jar
    ports:
     - 8083:8083
     - 5005:5005
    links:
     - kafka
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_source_connect_statuses
